### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by diriano** [NGSEP/NGSEPcore#53]
Hello Jorge,

I am trying the transposon finder in sugarcane, a genome of around 10Gbp, and I keep getting an out of memory error despite increasing heap size (Xmx) to 10g.
Any suggestion what to do? Hopefully that does not involve spliting the input file?
Best,
Diego

**Comment by jduitama** [comment]
Hi Diego

For a genome of 10 Gbp you probably need more than 10 Gb of RAM. Try running with at least 32 Gbp and let me know how things go.

Best regards

Jorge

**Comment by diriano** [comment]
Hi @jduitama and @Rem1burwell ,
I appreciate your feedback.

I thought that the amount of required resources would be more a function of the size of the TE database rather than the size of the genome.

Would it be possible to process the genome in smallish chunks? This could perhaps alleviate the need for RAM.

Best,
Diego

**Comment by diriano** [comment]
Dear @jduitama ,
I am trying to compile, without sucess, with JDK 11.0.13.

I am getting the following error: 

```
src/ngsep/sequences/RawRead.java:50: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static RawRead load(BufferedReader in) throws IOException {
	                      ^
src/ngsep/transposons/TransposableElementLibraryFilter.java:135: error: incompatible types: try-with-resources not applicable to variable type
		try (ThreadPoolExecutor pool = new ThreadPoolExecutor(numThreads, numThreads, n, TimeUnit.SECONDS,
		                        ^
    (ThreadPoolExecutor cannot be converted to AutoCloseable)
src/ngsep/transposons/TransposableElementsFinder.java:290: error: incompatible types: try-with-resources not applicable to variable type
		try (ThreadPoolExecutor pool = new ThreadPoolExecutor(numThreads, numThreads, knownTransposons.size(), TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>())) {
		                        ^
    (ThreadPoolExecutor cannot be converted to AutoCloseable)
src/ngsep/transposons/TransposableElementsFinder.java:457: error: incompatible types: try-with-resources not applicable to variable type
		try (ThreadPoolExecutor pool = new ThreadPoolExecutor(numThreads, numThreads, nonRedundantAnn.size(), TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>())) {
		                        ^
    (ThreadPoolExecutor cannot be converted to AutoCloseable)
3 errors
1 warning
```
I will try other versions of JDK and let you know.
Thanks,
Diego

**Comment by diriano** [comment]
I was able to compile with JDK 24.0.1 . Perhaps that is worth mentioning in the documentation.
